### ISSUE TITLE
32bit support for games

### ISSUE THREAD

**Issue by sinaflan** [serpent-linux/bootstrap-scripts#1]
> we'll just focus on x86_64 hardware

subj?

**Comment by Wazzaps** [comment]
Perhaps an approach like Steam where all of the libs are in a container

**Comment by ikeycode** [comment]
bootstrap-scripts is just for the initial 3-stages of bootstrap. For Steam/games/etc we'll eventually look at container solutions as we don't want to design the distribution around a specific application (like Steam or Chrome etc)

**Comment by ikeycode** [comment]
Closing this as its not applicable to bootstrap-scripts. Obviously we'll want support in future for containerized games as long as they don't influence core OS design. :) (Spoiler: I like gaming.)
