### ISSUE TITLE
OpenBootstrap

### ISSUE THREAD

**Issue by jwinnie** [serpent-linux/bootstrap-scripts#2]
Hello! I'm a former Solus user and I think Serpent Linux seems really cool.

A while back I wrote a modular Python framework for writing bootstrapping scripts. Maybe you guys can make use of it somehow.

https://gitlab.com/popularis-os/openbootstrap

**Comment by ikeycode** [comment]
Hi @jwinnie - while openbootstrap certainly looks awesome, I'm not sure it goes with what this project is doing.

Ours is the dirty, simple approach to maintainence, and is designed purely to bootstrap a Clang/LLVM/libc++/musl 
root image in 3 stages. Eventually it will be extended to cross-compile for Serpent from Serpent, targeting ARM.
